### ISSUE TITLE
Is there a way to auto report any occurrence of an app error?

### ISSUE THREAD

**Issue by marcelgruber** [stvp/rollbar#27]
I know this is possible as I've done it in other tech stacks. Currently I'm just reporting manually any place in my app that could throw an error. Which is about 50 occurrences. I suppose the question is, if we wanted to explore this, where would we likely put this code? Or is it not so simple in Go? I understand that errors can bubble up, and some errors can be repressed or handled before they bubble all the way up. But is there a way to inject the rollbar send code inside of the default error handler? Cheers

**Comment by bpo** [comment]
Let me know if I'm misreading, but I think you're referring to exception handling here. Go doesn't have such a concept. You can report errors anywhere in the stack by handling the error explicitly. You can pass errors up the stack (possibly to some more general error reporter) by explicit return value, not by catching and throwing. If you're new to error handling in Go, [this article may be useful](https://blog.golang.org/error-handling-and-go)

**Comment by marcelgruber** [comment]
Hmmm, I suppose that I AM talking about exception handling then. I got confused because in a recent PHP project the framework I used had a function that was called whenever an exception was thrown and thus any exception that ever happened would automatically be reported because I was able to slap the reporting line in there. That's what was messing with me. 

After reading a bit, you are in fact right that Go has no exceptions, at least in the conventional sense. https://golang.org/doc/faq#exceptions

So then I suppose my question would be, how would one simplify the process of having to go through every single error check and adding the reporting code lines? Is it even possible? It's fine for 10 cases, but what if we had a big old app with hundreds of error checks?

**Comment by bpo** [comment]
> So then I suppose my question would be, how would one simplify the process of having to go through every single error check and adding the reporting code lines? Is it even possible? It's fine for 10 cases, but what if we had a big old app with hundreds of error checks?

This is a common topic of discussion. One way to think of this issue is to realize that exceptions in other languages are just a secondary method of returning values (i.e. error values) from a function. A common pattern in Go is to have the second of two return values be an error type. If you have an error result, you can pass it back to the caller on and on until the point at which you want to act on it, using this package or whatever other logic your program demands.

This is a longer discussion of application design, well beyond the scope of `stvp/rollbar`, so I'm going to close this one out. In addition to the article I linked to earlier there are lots of resources online about error handling in Go that would probably be better resources than my ad libbing in a github issue :)
